# This is a map from the old wayf entries to the actual metadata entityIDs
idpmap = { 
    "http://www.grnet.gr/aai:edugain.gr": "http://edugain-login.grnet.gr/ShiBE-R/ShiBEWebRequester",
    "http://www.grnet.gr/aai:panepisthmio.gr": "https://aai-tei.ucnet.uoc.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:admin.grnet.gr": "https://blackbox.admin.grnet.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:aegean.gr": "https://grnetbox.aegean.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:aua.gr": "https://grnetbox.aua.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:aueb.gr": "https://grnetbox.aueb.gr/shibboleth-idp/",
#    "http://www.grnet.gr/aai:ccf.auth.gr": "https://grnetbox.ccf.auth.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:teicrete.gr": "https://grnetbox.chania.teicrete.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:cti.gr": "https://grnetbox.cti.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:duth.gr": "https://grnetbox.duth.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:hua.gr": "https://grnetbox.hua.gr/shibboleth-idp/",
#    "http://www.grnet.gr/aai:noc.ntua.gr": "https://grnetbox.noc.ntua.gr/shibboleth-idp/",
#    "http://www.grnet.gr/aai:noc.uoa.gr": "https://grnetbox.noc.uoa.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:teiath.gr": "https://grnetbox.teiath.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:teimes.gr": "https://grnetbox.teimes.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:teiser.gr": "https://grnetbox.teiser.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:tuc.gr": "https://grnetbox.tuc.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:ucnet.uoc.gr": "https://grnetbox.ucnet.uoc.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:uoi.gr": "https://grnetbox.uoi.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:uth.gr": "https://grnetbox.uth.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:ekt.gr": "https://idp.ekt.gr/idp/shibboleth",
    "http://www.grnet.gr/aai:hua.gr": "https://idp.hua.gr/idp/shibboleth",
    "http://www.grnet.gr/aai:ntua.gr": "https://idp.ntua.gr/shibboleth",
    "http://www.grnet.gr/aai:heraklion.teicrete.gr": "https://idp.teicrete.gr/idp/shibboleth",
    "http://www.grnet.gr/aai:uoa.gr": "https://idp.uoa.gr/idp/shibboleth",
    "http://www.grnet.gr/aai:uop.gr": "https://idp.uop.gr/idp/shibboleth",
    "http://www.grnet.gr/aai:upatras.gr": "https://idp.upatras.gr/shibboleth-idp/",
    "http://www.grnet.gr/aai:auth.gr": "https://login.auth.gr/shibboleth-idp/",
#    "http://www.grnet.gr/aai:edunet.gr": "https://login.edunet.gr/shibboleth-idp/",
}
